version: '3.8'
x-common-variables: &common-variables
    PYTHONUNBUFFERED: 1
    api_id:
    api_hash:
    admin:
    tapswap_clicker: on
    hamster_clicker: on
    cexio_clicker: on
    auto_upgrade: true
    max_days_for_return: 15
    max_charge_level: 5
    max_energy_level: 10
    max_tap_level: 10
    cexio_ref_code:
    version: 1.1.1
services:
    app:
        build: .
        image: ghcr.io/mahdishariatzade/autoclicker:latest
        network_mode: host
        environment:
            <<: *common-variables
            accounts: #
